name: TEPIC
channels: 
  - bioconda
  - conda-forge
  - r
dependencies:
  - compilers
  - bedtools
  - numpy
  - scipy
  - twobitreader
  - r-gplots
  - r-ggplot2
  - r-glmnet
  - r-domc
  - r-reshape2
  - r-gridextra

